sudo: false
language: scala
scala:
  - 2.13.5
jdk:
  - openjdk8
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 14
  - nvm use 14
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete